name: FriendPlugin
version: 1.0
author: IamElBoi
main: fr.iamelboi.friendplugin.Main
commands:
  friend-add:
    description: Allows a player to send a friend request to another player
    usage: /friend-add <username>
    permission: friendplugin.friendadd
  friend-remove:
    description: Allows a player to remove a friend from his friend lisr
    usage: /friend-remove <username>
    permission: friendplugin.friendremove


  test:
    description: Ceci est une commande de test
    permission: test.use
  alert:
    description: Ceci est un broadcast custom
    permission: bc.use