name: FriendPlugin
version: 1.0
author: IamElBoi
main: fr.iamelboi.friendplugin.Main
commands:
  friend-add:
    description: Allows a player to add a friend
    usage: /friend-add <username>
    permission: friendplugin.friendadd


  test:
    description: Ceci est une commande de test
    permission: test.use
  alert:
    description: Ceci est un broadcast custom
    permission: bc.use